
--create database ECOMMERCE;
---   VALIDAR AS TABELAS COM O GRUPO E PROF DE BANCO DE DADOS


CREATE TABLE CATEGORIA(
CATEGORIA_ID INT NOT NULL,
NOME VARCHAR2(100),
DESCRICAO VARCHAR2(100),
CONSTRAINT PK_CATEGORIA PRIMARY KEY (CATEGORIA_ID)
);

CREATE TABLE PRODUTO(
PRODUTO_ID INTEGER NOT NULL,
CATEGORIA_ID INT NOT NULL,
FOTO VARCHAR2(100),
PRECO NUMERIC(15,2),
DESCRICAO VARCHAR2(100),
INFORMACOES_TECNICAS VARCHAR2(100),
CONSTRAINT PK_PRODUTO PRIMARY KEY(PRODUTO_ID),
CONSTRAINT FK_CATEGORIA FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID)
);


CREATE TABLE USUARIO(
USUARIO_ID INT NOT NULL,
NOME VARCHAR2(100),
CPF VARCHAR2(100),
CIDADE VARCHAR2(100),
ESTADO VARCHAR2(100),
CEP VARCHAR2(100),
TELEFONE_RESIDENCIAL VARCHAR2(15),
TELEFONE_COMERCIA VARCHAR2(15),
TELEFONE_MOVEL VARCHAR2(15),
SENHA VARCHAR2(20),
ENDERECO VARCHAR2(100),
EMAIL VARCHAR2(100),
CONSTRAINT PK_USUARIO PRIMARY KEY(USUARIO_ID)
);


CREATE TABLE AVALIACAO(
AVALIACAO_ID INT NOT NULL,
PRODUTO_ID INT NOT NULL,
USUARIO_ID INT NOT NULL,
CLIENTE VARCHAR2(100),
NOTA NUMERIC(2,2),
COMENTARIO VARCHAR2(100),
EMAIL VARCHAR2(100),
CONSTRAINT PK_AVALIACAO PRIMARY KEY(AVALIACAO_ID),
CONSTRAINT FK_PRODUTO_AVALIACAO FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID),
CONSTRAINT FK_USUARIO_AVALIACAO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);



CREATE TABLE LISTA_DE_COMPRA(
LISTA_DE_COMPRA_ID INT NOT NULL,
USUARIO_ID INT NOT NULL,
CONSTRAINT PK_LISTA_DE_COMPRA PRIMARY KEY(LISTA_DE_COMPRA_ID),
CONSTRAINT FK_USUARIO_LISTA FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);


CREATE TABLE ITEM_DE_PEDIDO(
PRODUTO_ID INT NOT NULL,
LISTA_DE_COMPRA_ID INT NOT NULL,
QTD INTEGER,
TOTAL NUMERIC(10,2),
CONSTRAINT FK_PRODUTO_ITEM_PEDIDO FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID),
CONSTRAINT FK_LISTA_DE_COMPRA_ITEM_PEDIDO FOREIGN KEY(LISTA_DE_COMPRA_ID) REFERENCES LISTA_DE_COMPRA(LISTA_DE_COMPRA_ID)
); 



CREATE TABLE PEDIDO(
PEDIDO_ID INT NOT NULL,
LISTA_DE_COMPRA_ID INT NOT NULL,
STATUS INT,
IDENTIFICADOR VARCHAR2(20),
PRECO_TOTAL NUMERIC(15,2),
NUMERO VARCHAR2(20),
DATA_DO_PEDIDO VARCHAR2(8),
DATA_DE_ENTREGA VARCHAR2(8),
CONSTRAINT PK_PEDIDO PRIMARY KEY(PEDIDO_ID),
CONSTRAINT FK_LISTA_DE_COMPRA_PEDIDO FOREIGN KEY(LISTA_DE_COMPRA_ID) REFERENCES LISTA_DE_COMPRA(LISTA_DE_COMPRA_ID)
);

CREATE TABLE PAGAMENTO(
PAGAMENTO_ID INT NOT NULL,
PEDIDO_ID INT NOT NULL,
STATUS INT,
VALOR_PAGO NUMERIC(15,2),
VALOR_PENDENTE NUMERIC(15,2),
CONSTRAINT PK_PAGAMENTO PRIMARY KEY(PAGAMENTO_ID),
CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY(PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID)
);
